baseURL = 'https://blog.dennishilhorst.nl/'
locale = 'nl-nl'
title = 'A blog by Dennis Hilhorst'
theme = 'stack'
metaDataFormat = "yaml"

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
identifier = "homelab-journey"
name = "Homelab Journey"
url = "/homelab-journey/"
weight = 10

[[menu.main]]
identifier = "packing-list"
name = "Packing List"
url = "/packing-list/"
weight = 10